Skips fragile tests that depends on error message from `click`.
We will change the test, but there is no way to patch all already released versions. So we need to skip the whole test for now.

Example failure:
```
FAIL: testPipelineEmptyFlagValue (__main__.PipelineTest)
PipelineTest.testPipelineEmptyFlagValue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tools/cli/commands/pipeline_test.py", line 115, in testPipelineEmptyFlagValue
    self.assertIn('option requires an argument', result.output)
AssertionError: 'option requires an argument' not found in "Error: Option '--pipeline_path' requires an argument.\n"
```
PiperOrigin-RevId: 374114216