Moves kubeflow e2e tests to a dedicated directory to prevent confusion in imports.
Because there is "proto" directory in "tfx/orchestration/kubeflow/", we cannot use proto-plus[1] package which has a colliding name "proto". It fails like following:
```
  File "/tmpfs/BUILD_ENV/.venv/lib/python3.7/site-packages/google/cloud/aiplatform_v1/types/user_action_reference.py", line 21, in <module>
    __protobuf__ = proto.module(
AttributeError: module 'proto' has no attribute 'module'
```
proto-plus is used in google libraries including google-aiplatform[2].

[1] https://github.com/googleapis/proto-plus-python
[2] https://github.com/googleapis/python-aiplatform

PiperOrigin-RevId: 368948743