Fix a bug in task_manager_test.py
`_FakeTaskScheduler.schedule` was raising an exception:
TypeError: __init__() got an unexpected keyword argument 'executor_output'
but tests weren't failing because they ignored the result.
PiperOrigin-RevId: 391373382