Remove flakky test asserts that depends on error message of the external library(click).
Example failure:
```
FAIL: testPipelineInvalidFlag (__main__.PipelineTest)
PipelineTest.testPipelineInvalidFlag
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tools/cli/commands/pipeline_test.py", line 95, in testPipelineInvalidFlag
    self.assertIn('no such option', result.output)
AssertionError: 'no such option' not found in "Usage: pipeline create [OPTIONS]\nTry 'pipeline create --help' for help.\n\nError: No such option: --pipeline_name (Possible options: --pipeline-path, --pipeline_path)\n"
```
PiperOrigin-RevId: 374529522